mssql:
  build:
    dockerfile: Dockerfile
  image: microsoft/mssql-server-linux:2017-latest
  container_name: 'gwf_sqlserver'
  ports:
    - 1433:1433
  environment:
    ACCEPT_EULA: Y
    SA_PASSWORD: P@ssw0rd
    MSSQL_PID : Developer